// Code generated by testparrot. DO NOT EDIT.

package postgres

import (
	model "github.com/go-jet/jet/v2/tests/postgres/gen/chinook/model"
	gotestparrot "github.com/xtruder/go-testparrot"
	"time"
)

func init() {
	gotestparrot.R.Load("TestJoinEverything", []gotestparrot.Recording{{
		Key: 0,
		Value: `
SELECT "Artist"."ArtistId" AS "Artist.ArtistId",
     "Artist"."Name" AS "Artist.Name",
     "Album"."AlbumId" AS "Album.AlbumId",
     "Album"."Title" AS "Album.Title",
     "Album"."ArtistId" AS "Album.ArtistId",
     "Track"."TrackId" AS "Track.TrackId",
     "Track"."Name" AS "Track.Name",
     "Track"."AlbumId" AS "Track.AlbumId",
     "Track"."MediaTypeId" AS "Track.MediaTypeId",
     "Track"."GenreId" AS "Track.GenreId",
     "Track"."Composer" AS "Track.Composer",
     "Track"."Milliseconds" AS "Track.Milliseconds",
     "Track"."Bytes" AS "Track.Bytes",
     "Track"."UnitPrice" AS "Track.UnitPrice",
     "Genre"."GenreId" AS "Genre.GenreId",
     "Genre"."Name" AS "Genre.Name",
     "MediaType"."MediaTypeId" AS "MediaType.MediaTypeId",
     "MediaType"."Name" AS "MediaType.Name",
     "PlaylistTrack"."PlaylistId" AS "PlaylistTrack.PlaylistId",
     "PlaylistTrack"."TrackId" AS "PlaylistTrack.TrackId",
     "Playlist"."PlaylistId" AS "Playlist.PlaylistId",
     "Playlist"."Name" AS "Playlist.Name",
     "Invoice"."InvoiceId" AS "Invoice.InvoiceId",
     "Invoice"."CustomerId" AS "Invoice.CustomerId",
     "Invoice"."InvoiceDate" AS "Invoice.InvoiceDate",
     "Invoice"."BillingAddress" AS "Invoice.BillingAddress",
     "Invoice"."BillingCity" AS "Invoice.BillingCity",
     "Invoice"."BillingState" AS "Invoice.BillingState",
     "Invoice"."BillingCountry" AS "Invoice.BillingCountry",
     "Invoice"."BillingPostalCode" AS "Invoice.BillingPostalCode",
     "Invoice"."Total" AS "Invoice.Total",
     "Customer"."CustomerId" AS "Customer.CustomerId",
     "Customer"."FirstName" AS "Customer.FirstName",
     "Customer"."LastName" AS "Customer.LastName",
     "Customer"."Company" AS "Customer.Company",
     "Customer"."Address" AS "Customer.Address",
     "Customer"."City" AS "Customer.City",
     "Customer"."State" AS "Customer.State",
     "Customer"."Country" AS "Customer.Country",
     "Customer"."PostalCode" AS "Customer.PostalCode",
     "Customer"."Phone" AS "Customer.Phone",
     "Customer"."Fax" AS "Customer.Fax",
     "Customer"."Email" AS "Customer.Email",
     "Customer"."SupportRepId" AS "Customer.SupportRepId",
     "Employee"."EmployeeId" AS "Employee.EmployeeId",
     "Employee"."LastName" AS "Employee.LastName",
     "Employee"."FirstName" AS "Employee.FirstName",
     "Employee"."Title" AS "Employee.Title",
     "Employee"."ReportsTo" AS "Employee.ReportsTo",
     "Employee"."BirthDate" AS "Employee.BirthDate",
     "Employee"."HireDate" AS "Employee.HireDate",
     "Employee"."Address" AS "Employee.Address",
     "Employee"."City" AS "Employee.City",
     "Employee"."State" AS "Employee.State",
     "Employee"."Country" AS "Employee.Country",
     "Employee"."PostalCode" AS "Employee.PostalCode",
     "Employee"."Phone" AS "Employee.Phone",
     "Employee"."Fax" AS "Employee.Fax",
     "Employee"."Email" AS "Employee.Email",
     "Manager"."EmployeeId" AS "Manager.EmployeeId",
     "Manager"."LastName" AS "Manager.LastName",
     "Manager"."FirstName" AS "Manager.FirstName",
     "Manager"."Title" AS "Manager.Title",
     "Manager"."ReportsTo" AS "Manager.ReportsTo",
     "Manager"."BirthDate" AS "Manager.BirthDate",
     "Manager"."HireDate" AS "Manager.HireDate",
     "Manager"."Address" AS "Manager.Address",
     "Manager"."City" AS "Manager.City",
     "Manager"."State" AS "Manager.State",
     "Manager"."Country" AS "Manager.Country",
     "Manager"."PostalCode" AS "Manager.PostalCode",
     "Manager"."Phone" AS "Manager.Phone",
     "Manager"."Fax" AS "Manager.Fax",
     "Manager"."Email" AS "Manager.Email"
FROM chinook."Artist"
     LEFT JOIN chinook."Album" ON ("Artist"."ArtistId" = "Album"."ArtistId")
     LEFT JOIN chinook."Track" ON ("Track"."AlbumId" = "Album"."AlbumId")
     LEFT JOIN chinook."Genre" ON ("Genre"."GenreId" = "Track"."GenreId")
     LEFT JOIN chinook."MediaType" ON ("MediaType"."MediaTypeId" = "Track"."MediaTypeId")
     LEFT JOIN chinook."PlaylistTrack" ON ("PlaylistTrack"."TrackId" = "Track"."TrackId")
     LEFT JOIN chinook."Playlist" ON ("Playlist"."PlaylistId" = "PlaylistTrack"."PlaylistId")
     LEFT JOIN chinook."InvoiceLine" ON ("InvoiceLine"."TrackId" = "Track"."TrackId")
     LEFT JOIN chinook."Invoice" ON ("Invoice"."InvoiceId" = "InvoiceLine"."InvoiceId")
     LEFT JOIN chinook."Customer" ON ("Customer"."CustomerId" = "Invoice"."CustomerId")
     LEFT JOIN chinook."Employee" ON ("Employee"."EmployeeId" = "Customer"."SupportRepId")
     LEFT JOIN chinook."Employee" AS "Manager" ON ("Manager"."EmployeeId" = "Employee"."ReportsTo")
ORDER BY "Artist"."ArtistId", "Album"."AlbumId", "Track"."TrackId", "Genre"."GenreId", "MediaType"."MediaTypeId", "Playlist"."PlaylistId", "Invoice"."InvoiceId", "Customer"."CustomerId";
`,
	}, {
		Key:   1,
		Value: []interface{}{},
	}, {
		Key:   2,
		Value: 275,
	}, {
		Key: 3,
		Value: struct {
			model.Artist
			Albums []struct {
				model.Album
				Tracks []struct {
					model.Track
					Genre     model.Genre
					MediaType model.MediaType
					Playlists []model.Playlist
					Invoices  []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}
				}
			}
		}{
			Albums: []struct {
				model.Album
				Tracks []struct {
					model.Track
					Genre     model.Genre
					MediaType model.MediaType
					Playlists []model.Playlist
					Invoices  []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}
				}
			}{{
				Album: model.Album{
					AlbumId:  int32(1),
					ArtistId: int32(1),
					Title:    "For Those About To Rock We Salute You",
				},
				Tracks: []struct {
					model.Track
					Genre     model.Genre
					MediaType model.MediaType
					Playlists []model.Playlist
					Invoices  []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}
				}{{
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Via Degli Scipioni, 43").(*string),
								City:         gotestparrot.Ptr("Rome").(*string),
								Country:      gotestparrot.Ptr("Italy").(*string),
								CustomerId:   int32(47),
								Email:        "lucas.mancini@yahoo.it",
								FirstName:    "Lucas",
								LastName:     "Mancini",
								Phone:        gotestparrot.Ptr("+39 06 39733434").(*string),
								PostalCode:   gotestparrot.Ptr("00192").(*string),
								State:        gotestparrot.Ptr("RM").(*string),
								SupportRepId: gotestparrot.Ptr(int32(5)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("7727B 41 Ave").(*string),
									BirthDate:  gotestparrot.Decode("1965-03-03T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("steve@chinookcorp.com").(*string),
									EmployeeId: int32(5),
									Fax:        gotestparrot.Ptr("1 (780) 836-9543").(*string),
									FirstName:  "Steve",
									HireDate:   gotestparrot.Decode("2003-10-17T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Johnson",
									Phone:      gotestparrot.Ptr("1 (780) 836-9987").(*string),
									PostalCode: gotestparrot.Ptr("T3B 1Y7").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Via Degli Scipioni, 43").(*string),
							BillingCity:       gotestparrot.Ptr("Rome").(*string),
							BillingCountry:    gotestparrot.Ptr("Italy").(*string),
							BillingPostalCode: gotestparrot.Ptr("00192").(*string),
							BillingState:      gotestparrot.Ptr("RM").(*string),
							CustomerId:        int32(47),
							InvoiceDate:       gotestparrot.Decode("2010-04-13T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(108),
							Total:             5.94,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}, {
						Name:       gotestparrot.Ptr("Heavy Metal Classic").(*string),
						PlaylistId: int32(17),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(11170334)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(343719),
						Name:         "For Those About To Rock (We Salute You)",
						TrackId:      int32(1),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Ullev�lsveien 14").(*string),
								City:         gotestparrot.Ptr("Oslo").(*string),
								Country:      gotestparrot.Ptr("Norway").(*string),
								CustomerId:   int32(4),
								Email:        "bjorn.hansen@yahoo.no",
								FirstName:    "Bj�rn",
								LastName:     "Hansen",
								Phone:        gotestparrot.Ptr("+47 22 44 22 22").(*string),
								PostalCode:   gotestparrot.Ptr("0171").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Ullev�lsveien 14").(*string),
							BillingCity:       gotestparrot.Ptr("Oslo").(*string),
							BillingCountry:    gotestparrot.Ptr("Norway").(*string),
							BillingPostalCode: gotestparrot.Ptr("0171").(*string),
							CustomerId:        int32(4),
							InvoiceDate:       gotestparrot.Decode("2009-01-02T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(2),
							Total:             3.96,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(6713451)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(205662),
						Name:         "Put The Finger On You",
						TrackId:      int32(6),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(7636561)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(233926),
						Name:         "Let's Get It Up",
						TrackId:      int32(7),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Ullev�lsveien 14").(*string),
								City:         gotestparrot.Ptr("Oslo").(*string),
								Country:      gotestparrot.Ptr("Norway").(*string),
								CustomerId:   int32(4),
								Email:        "bjorn.hansen@yahoo.no",
								FirstName:    "Bj�rn",
								LastName:     "Hansen",
								Phone:        gotestparrot.Ptr("+47 22 44 22 22").(*string),
								PostalCode:   gotestparrot.Ptr("0171").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Ullev�lsveien 14").(*string),
							BillingCity:       gotestparrot.Ptr("Oslo").(*string),
							BillingCountry:    gotestparrot.Ptr("Norway").(*string),
							BillingPostalCode: gotestparrot.Ptr("0171").(*string),
							CustomerId:        int32(4),
							InvoiceDate:       gotestparrot.Decode("2009-01-02T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(2),
							Total:             3.96,
						},
					}, {
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("5112 48 Street").(*string),
								City:         gotestparrot.Ptr("Yellowknife").(*string),
								Country:      gotestparrot.Ptr("Canada").(*string),
								CustomerId:   int32(33),
								Email:        "ellie.sullivan@shaw.ca",
								FirstName:    "Ellie",
								LastName:     "Sullivan",
								Phone:        gotestparrot.Ptr("+1 (867) 920-2233").(*string),
								PostalCode:   gotestparrot.Ptr("X1A 1N6").(*string),
								State:        gotestparrot.Ptr("NT").(*string),
								SupportRepId: gotestparrot.Ptr(int32(3)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("1111 6 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1973-08-29T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("jane@chinookcorp.com").(*string),
									EmployeeId: int32(3),
									Fax:        gotestparrot.Ptr("+1 (403) 262-6712").(*string),
									FirstName:  "Jane",
									HireDate:   gotestparrot.Decode("2002-04-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Peacock",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5M5").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("5112 48 Street").(*string),
							BillingCity:       gotestparrot.Ptr("Yellowknife").(*string),
							BillingCountry:    gotestparrot.Ptr("Canada").(*string),
							BillingPostalCode: gotestparrot.Ptr("X1A 1N6").(*string),
							BillingState:      gotestparrot.Ptr("NT").(*string),
							CustomerId:        int32(33),
							InvoiceDate:       gotestparrot.Decode("2011-07-25T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(214),
							Total:             8.91,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(6852860)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(210834),
						Name:         "Inject The Venom",
						TrackId:      int32(8),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Via Degli Scipioni, 43").(*string),
								City:         gotestparrot.Ptr("Rome").(*string),
								Country:      gotestparrot.Ptr("Italy").(*string),
								CustomerId:   int32(47),
								Email:        "lucas.mancini@yahoo.it",
								FirstName:    "Lucas",
								LastName:     "Mancini",
								Phone:        gotestparrot.Ptr("+39 06 39733434").(*string),
								PostalCode:   gotestparrot.Ptr("00192").(*string),
								State:        gotestparrot.Ptr("RM").(*string),
								SupportRepId: gotestparrot.Ptr(int32(5)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("7727B 41 Ave").(*string),
									BirthDate:  gotestparrot.Decode("1965-03-03T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("steve@chinookcorp.com").(*string),
									EmployeeId: int32(5),
									Fax:        gotestparrot.Ptr("1 (780) 836-9543").(*string),
									FirstName:  "Steve",
									HireDate:   gotestparrot.Decode("2003-10-17T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Johnson",
									Phone:      gotestparrot.Ptr("1 (780) 836-9987").(*string),
									PostalCode: gotestparrot.Ptr("T3B 1Y7").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Via Degli Scipioni, 43").(*string),
							BillingCity:       gotestparrot.Ptr("Rome").(*string),
							BillingCountry:    gotestparrot.Ptr("Italy").(*string),
							BillingPostalCode: gotestparrot.Ptr("00192").(*string),
							BillingState:      gotestparrot.Ptr("RM").(*string),
							CustomerId:        int32(47),
							InvoiceDate:       gotestparrot.Decode("2010-04-13T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(108),
							Total:             5.94,
						},
					}, {
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Qe 7 Bloco G").(*string),
								City:         gotestparrot.Ptr("Bras�lia").(*string),
								Country:      gotestparrot.Ptr("Brazil").(*string),
								CustomerId:   int32(13),
								Email:        "fernadaramos4@uol.com.br",
								Fax:          gotestparrot.Ptr("+55 (61) 3363-7855").(*string),
								FirstName:    "Fernanda",
								LastName:     "Ramos",
								Phone:        gotestparrot.Ptr("+55 (61) 3363-5547").(*string),
								PostalCode:   gotestparrot.Ptr("71020-677").(*string),
								State:        gotestparrot.Ptr("DF").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Qe 7 Bloco G").(*string),
							BillingCity:       gotestparrot.Ptr("Bras�lia").(*string),
							BillingCountry:    gotestparrot.Ptr("Brazil").(*string),
							BillingPostalCode: gotestparrot.Ptr("71020-677").(*string),
							BillingState:      gotestparrot.Ptr("DF").(*string),
							CustomerId:        int32(13),
							InvoiceDate:       gotestparrot.Decode("2012-11-01T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(319),
							Total:             8.91,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(6599424)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(203102),
						Name:         "Snowballed",
						TrackId:      int32(9),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Ullev�lsveien 14").(*string),
								City:         gotestparrot.Ptr("Oslo").(*string),
								Country:      gotestparrot.Ptr("Norway").(*string),
								CustomerId:   int32(4),
								Email:        "bjorn.hansen@yahoo.no",
								FirstName:    "Bj�rn",
								LastName:     "Hansen",
								Phone:        gotestparrot.Ptr("+47 22 44 22 22").(*string),
								PostalCode:   gotestparrot.Ptr("0171").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Ullev�lsveien 14").(*string),
							BillingCity:       gotestparrot.Ptr("Oslo").(*string),
							BillingCountry:    gotestparrot.Ptr("Norway").(*string),
							BillingPostalCode: gotestparrot.Ptr("0171").(*string),
							CustomerId:        int32(4),
							InvoiceDate:       gotestparrot.Decode("2009-01-02T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(2),
							Total:             3.96,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(8611245)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(263497),
						Name:         "Evil Walks",
						TrackId:      int32(10),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(6566314)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(199836),
						Name:         "C.O.D.",
						TrackId:      int32(11),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Ullev�lsveien 14").(*string),
								City:         gotestparrot.Ptr("Oslo").(*string),
								Country:      gotestparrot.Ptr("Norway").(*string),
								CustomerId:   int32(4),
								Email:        "bjorn.hansen@yahoo.no",
								FirstName:    "Bj�rn",
								LastName:     "Hansen",
								Phone:        gotestparrot.Ptr("+47 22 44 22 22").(*string),
								PostalCode:   gotestparrot.Ptr("0171").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Ullev�lsveien 14").(*string),
							BillingCity:       gotestparrot.Ptr("Oslo").(*string),
							BillingCountry:    gotestparrot.Ptr("Norway").(*string),
							BillingPostalCode: gotestparrot.Ptr("0171").(*string),
							CustomerId:        int32(4),
							InvoiceDate:       gotestparrot.Decode("2009-01-02T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(2),
							Total:             3.96,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(8596840)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(263288),
						Name:         "Breaking The Rules",
						TrackId:      int32(12),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Via Degli Scipioni, 43").(*string),
								City:         gotestparrot.Ptr("Rome").(*string),
								Country:      gotestparrot.Ptr("Italy").(*string),
								CustomerId:   int32(47),
								Email:        "lucas.mancini@yahoo.it",
								FirstName:    "Lucas",
								LastName:     "Mancini",
								Phone:        gotestparrot.Ptr("+39 06 39733434").(*string),
								PostalCode:   gotestparrot.Ptr("00192").(*string),
								State:        gotestparrot.Ptr("RM").(*string),
								SupportRepId: gotestparrot.Ptr(int32(5)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("7727B 41 Ave").(*string),
									BirthDate:  gotestparrot.Decode("1965-03-03T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("steve@chinookcorp.com").(*string),
									EmployeeId: int32(5),
									Fax:        gotestparrot.Ptr("1 (780) 836-9543").(*string),
									FirstName:  "Steve",
									HireDate:   gotestparrot.Decode("2003-10-17T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Johnson",
									Phone:      gotestparrot.Ptr("1 (780) 836-9987").(*string),
									PostalCode: gotestparrot.Ptr("T3B 1Y7").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Via Degli Scipioni, 43").(*string),
							BillingCity:       gotestparrot.Ptr("Rome").(*string),
							BillingCountry:    gotestparrot.Ptr("Italy").(*string),
							BillingPostalCode: gotestparrot.Ptr("00192").(*string),
							BillingState:      gotestparrot.Ptr("RM").(*string),
							CustomerId:        int32(47),
							InvoiceDate:       gotestparrot.Decode("2010-04-13T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(108),
							Total:             5.94,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(6706347)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(205688),
						Name:         "Night Of The Long Knives",
						TrackId:      int32(13),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("5112 48 Street").(*string),
								City:         gotestparrot.Ptr("Yellowknife").(*string),
								Country:      gotestparrot.Ptr("Canada").(*string),
								CustomerId:   int32(33),
								Email:        "ellie.sullivan@shaw.ca",
								FirstName:    "Ellie",
								LastName:     "Sullivan",
								Phone:        gotestparrot.Ptr("+1 (867) 920-2233").(*string),
								PostalCode:   gotestparrot.Ptr("X1A 1N6").(*string),
								State:        gotestparrot.Ptr("NT").(*string),
								SupportRepId: gotestparrot.Ptr(int32(3)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("1111 6 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1973-08-29T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("jane@chinookcorp.com").(*string),
									EmployeeId: int32(3),
									Fax:        gotestparrot.Ptr("+1 (403) 262-6712").(*string),
									FirstName:  "Jane",
									HireDate:   gotestparrot.Decode("2002-04-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Peacock",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5M5").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("5112 48 Street").(*string),
							BillingCity:       gotestparrot.Ptr("Yellowknife").(*string),
							BillingCountry:    gotestparrot.Ptr("Canada").(*string),
							BillingPostalCode: gotestparrot.Ptr("X1A 1N6").(*string),
							BillingState:      gotestparrot.Ptr("NT").(*string),
							CustomerId:        int32(33),
							InvoiceDate:       gotestparrot.Decode("2011-07-25T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(214),
							Total:             8.91,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(1)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(8817038)).(*int32),
						Composer:     gotestparrot.Ptr("Angus Young, Malcolm Young, Brian Johnson").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(270863),
						Name:         "Spellbound",
						TrackId:      int32(14),
						UnitPrice:    0.99,
					},
				}},
			}, {
				Album: model.Album{
					AlbumId:  int32(4),
					ArtistId: int32(1),
					Title:    "Let There Be Rock",
				},
				Tracks: []struct {
					model.Track
					Genre     model.Genre
					MediaType model.MediaType
					Playlists []model.Playlist
					Invoices  []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}
				}{{
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Qe 7 Bloco G").(*string),
								City:         gotestparrot.Ptr("Bras�lia").(*string),
								Country:      gotestparrot.Ptr("Brazil").(*string),
								CustomerId:   int32(13),
								Email:        "fernadaramos4@uol.com.br",
								Fax:          gotestparrot.Ptr("+55 (61) 3363-7855").(*string),
								FirstName:    "Fernanda",
								LastName:     "Ramos",
								Phone:        gotestparrot.Ptr("+55 (61) 3363-5547").(*string),
								PostalCode:   gotestparrot.Ptr("71020-677").(*string),
								State:        gotestparrot.Ptr("DF").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Qe 7 Bloco G").(*string),
							BillingCity:       gotestparrot.Ptr("Bras�lia").(*string),
							BillingCountry:    gotestparrot.Ptr("Brazil").(*string),
							BillingPostalCode: gotestparrot.Ptr("71020-677").(*string),
							BillingState:      gotestparrot.Ptr("DF").(*string),
							CustomerId:        int32(13),
							InvoiceDate:       gotestparrot.Decode("2012-11-01T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(319),
							Total:             8.91,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(10847611)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(331180),
						Name:         "Go Down",
						TrackId:      int32(15),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Gr�trystraat 63").(*string),
								City:         gotestparrot.Ptr("Brussels").(*string),
								Country:      gotestparrot.Ptr("Belgium").(*string),
								CustomerId:   int32(8),
								Email:        "daan_peeters@apple.be",
								FirstName:    "Daan",
								LastName:     "Peeters",
								Phone:        gotestparrot.Ptr("+32 02 219 03 03").(*string),
								PostalCode:   gotestparrot.Ptr("1000").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Gr�trystraat 63").(*string),
							BillingCity:       gotestparrot.Ptr("Brussels").(*string),
							BillingCountry:    gotestparrot.Ptr("Belgium").(*string),
							BillingPostalCode: gotestparrot.Ptr("1000").(*string),
							CustomerId:        int32(8),
							InvoiceDate:       gotestparrot.Decode("2009-01-03T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(3),
							Total:             5.94,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(7032162)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(215196),
						Name:         "Dog Eat Dog",
						TrackId:      int32(16),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(12021261)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(366654),
						Name:         "Let There Be Rock",
						TrackId:      int32(17),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(8776140)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(267728),
						Name:         "Bad Boy Boogie",
						TrackId:      int32(18),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("113 Lupus St").(*string),
								City:         gotestparrot.Ptr("London").(*string),
								Country:      gotestparrot.Ptr("United Kingdom").(*string),
								CustomerId:   int32(53),
								Email:        "phil.hughes@gmail.com",
								FirstName:    "Phil",
								LastName:     "Hughes",
								Phone:        gotestparrot.Ptr("+44 020 7976 5722").(*string),
								PostalCode:   gotestparrot.Ptr("SW1V 3EN").(*string),
								SupportRepId: gotestparrot.Ptr(int32(3)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("1111 6 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1973-08-29T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("jane@chinookcorp.com").(*string),
									EmployeeId: int32(3),
									Fax:        gotestparrot.Ptr("+1 (403) 262-6712").(*string),
									FirstName:  "Jane",
									HireDate:   gotestparrot.Decode("2002-04-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Peacock",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5M5").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("113 Lupus St").(*string),
							BillingCity:       gotestparrot.Ptr("London").(*string),
							BillingCountry:    gotestparrot.Ptr("United Kingdom").(*string),
							BillingPostalCode: gotestparrot.Ptr("SW1V 3EN").(*string),
							CustomerId:        int32(53),
							InvoiceDate:       gotestparrot.Decode("2010-04-16T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(109),
							Total:             8.91,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(10617116)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(325041),
						Name:         "Problem Child",
						TrackId:      int32(19),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Gr�trystraat 63").(*string),
								City:         gotestparrot.Ptr("Brussels").(*string),
								Country:      gotestparrot.Ptr("Belgium").(*string),
								CustomerId:   int32(8),
								Email:        "daan_peeters@apple.be",
								FirstName:    "Daan",
								LastName:     "Peeters",
								Phone:        gotestparrot.Ptr("+32 02 219 03 03").(*string),
								PostalCode:   gotestparrot.Ptr("1000").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Gr�trystraat 63").(*string),
							BillingCity:       gotestparrot.Ptr("Brussels").(*string),
							BillingCountry:    gotestparrot.Ptr("Belgium").(*string),
							BillingPostalCode: gotestparrot.Ptr("1000").(*string),
							CustomerId:        int32(8),
							InvoiceDate:       gotestparrot.Decode("2009-01-03T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(3),
							Total:             5.94,
						},
					}, {
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("5112 48 Street").(*string),
								City:         gotestparrot.Ptr("Yellowknife").(*string),
								Country:      gotestparrot.Ptr("Canada").(*string),
								CustomerId:   int32(33),
								Email:        "ellie.sullivan@shaw.ca",
								FirstName:    "Ellie",
								LastName:     "Sullivan",
								Phone:        gotestparrot.Ptr("+1 (867) 920-2233").(*string),
								PostalCode:   gotestparrot.Ptr("X1A 1N6").(*string),
								State:        gotestparrot.Ptr("NT").(*string),
								SupportRepId: gotestparrot.Ptr(int32(3)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("1111 6 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1973-08-29T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("jane@chinookcorp.com").(*string),
									EmployeeId: int32(3),
									Fax:        gotestparrot.Ptr("+1 (403) 262-6712").(*string),
									FirstName:  "Jane",
									HireDate:   gotestparrot.Decode("2002-04-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Peacock",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5M5").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("5112 48 Street").(*string),
							BillingCity:       gotestparrot.Ptr("Yellowknife").(*string),
							BillingCountry:    gotestparrot.Ptr("Canada").(*string),
							BillingPostalCode: gotestparrot.Ptr("X1A 1N6").(*string),
							BillingState:      gotestparrot.Ptr("NT").(*string),
							CustomerId:        int32(33),
							InvoiceDate:       gotestparrot.Decode("2011-07-25T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(214),
							Total:             8.91,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(12066294)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(369319),
						Name:         "Overdose",
						TrackId:      int32(20),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					Invoices: []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}{{
						Customer: struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}{
							Customer: model.Customer{
								Address:      gotestparrot.Ptr("Qe 7 Bloco G").(*string),
								City:         gotestparrot.Ptr("Bras�lia").(*string),
								Country:      gotestparrot.Ptr("Brazil").(*string),
								CustomerId:   int32(13),
								Email:        "fernadaramos4@uol.com.br",
								Fax:          gotestparrot.Ptr("+55 (61) 3363-7855").(*string),
								FirstName:    "Fernanda",
								LastName:     "Ramos",
								Phone:        gotestparrot.Ptr("+55 (61) 3363-5547").(*string),
								PostalCode:   gotestparrot.Ptr("71020-677").(*string),
								State:        gotestparrot.Ptr("DF").(*string),
								SupportRepId: gotestparrot.Ptr(int32(4)).(*int32),
							},
							Employee: &struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}{
								Employee: model.Employee{
									Address:    gotestparrot.Ptr("683 10 Street SW").(*string),
									BirthDate:  gotestparrot.Decode("1947-09-19T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("margaret@chinookcorp.com").(*string),
									EmployeeId: int32(4),
									Fax:        gotestparrot.Ptr("+1 (403) 263-4289").(*string),
									FirstName:  "Margaret",
									HireDate:   gotestparrot.Decode("2003-05-03T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Park",
									Phone:      gotestparrot.Ptr("+1 (403) 263-4423").(*string),
									PostalCode: gotestparrot.Ptr("T2P 5G3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(2)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Support Agent").(*string),
								},
								Manager: &model.Employee{
									Address:    gotestparrot.Ptr("825 8 Ave SW").(*string),
									BirthDate:  gotestparrot.Decode("1958-12-08T00:00:00Z", &time.Time{}).(*time.Time),
									City:       gotestparrot.Ptr("Calgary").(*string),
									Country:    gotestparrot.Ptr("Canada").(*string),
									Email:      gotestparrot.Ptr("nancy@chinookcorp.com").(*string),
									EmployeeId: int32(2),
									Fax:        gotestparrot.Ptr("+1 (403) 262-3322").(*string),
									FirstName:  "Nancy",
									HireDate:   gotestparrot.Decode("2002-05-01T00:00:00Z", &time.Time{}).(*time.Time),
									LastName:   "Edwards",
									Phone:      gotestparrot.Ptr("+1 (403) 262-3443").(*string),
									PostalCode: gotestparrot.Ptr("T2P 2T3").(*string),
									ReportsTo:  gotestparrot.Ptr(int32(1)).(*int32),
									State:      gotestparrot.Ptr("AB").(*string),
									Title:      gotestparrot.Ptr("Sales Manager").(*string),
								},
							},
						},
						Invoice: model.Invoice{
							BillingAddress:    gotestparrot.Ptr("Qe 7 Bloco G").(*string),
							BillingCity:       gotestparrot.Ptr("Bras�lia").(*string),
							BillingCountry:    gotestparrot.Ptr("Brazil").(*string),
							BillingPostalCode: gotestparrot.Ptr("71020-677").(*string),
							BillingState:      gotestparrot.Ptr("DF").(*string),
							CustomerId:        int32(13),
							InvoiceDate:       gotestparrot.Decode("2012-11-01T00:00:00Z", time.Time{}).(time.Time),
							InvoiceId:         int32(319),
							Total:             8.91,
						},
					}},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(8331286)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(254380),
						Name:         "Hell Ain't A Bad Place To Be",
						TrackId:      int32(21),
						UnitPrice:    0.99,
					},
				}, {
					Genre: model.Genre{
						GenreId: int32(1),
						Name:    gotestparrot.Ptr("Rock").(*string),
					},
					MediaType: model.MediaType{
						MediaTypeId: int32(1),
						Name:        gotestparrot.Ptr("MPEG audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(4)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(10547154)).(*int32),
						Composer:     gotestparrot.Ptr("AC/DC").(*string),
						GenreId:      gotestparrot.Ptr(int32(1)).(*int32),
						MediaTypeId:  int32(1),
						Milliseconds: int32(323761),
						Name:         "Whole Lotta Rosie",
						TrackId:      int32(22),
						UnitPrice:    0.99,
					},
				}},
			}},
			Artist: model.Artist{
				ArtistId: int32(1),
				Name:     gotestparrot.Ptr("AC/DC").(*string),
			},
		},
	}, {
		Key: 4,
		Value: struct {
			model.Artist
			Albums []struct {
				model.Album
				Tracks []struct {
					model.Track
					Genre     model.Genre
					MediaType model.MediaType
					Playlists []model.Playlist
					Invoices  []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}
				}
			}
		}{
			Albums: []struct {
				model.Album
				Tracks []struct {
					model.Track
					Genre     model.Genre
					MediaType model.MediaType
					Playlists []model.Playlist
					Invoices  []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}
				}
			}{{
				Album: model.Album{
					AlbumId:  int32(347),
					ArtistId: int32(275),
					Title:    "Koyaanisqatsi (Soundtrack from the Motion Picture)",
				},
				Tracks: []struct {
					model.Track
					Genre     model.Genre
					MediaType model.MediaType
					Playlists []model.Playlist
					Invoices  []struct {
						model.Invoice
						Customer struct {
							model.Customer
							Employee *struct {
								model.Employee
								Manager *model.Employee `alias:"Manager"`
							}
						}
					}
				}{{
					Genre: model.Genre{
						GenreId: int32(10),
						Name:    gotestparrot.Ptr("Soundtrack").(*string),
					},
					MediaType: model.MediaType{
						MediaTypeId: int32(2),
						Name:        gotestparrot.Ptr("Protected AAC audio file").(*string),
					},
					Playlists: []model.Playlist{{
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(1),
					}, {
						Name:       gotestparrot.Ptr("90�s Music").(*string),
						PlaylistId: int32(5),
					}, {
						Name:       gotestparrot.Ptr("Music").(*string),
						PlaylistId: int32(8),
					}, {
						Name:       gotestparrot.Ptr("Classical").(*string),
						PlaylistId: int32(12),
					}, {
						Name:       gotestparrot.Ptr("Classical 101 - Deep Cuts").(*string),
						PlaylistId: int32(13),
					}},
					Track: model.Track{
						AlbumId:      gotestparrot.Ptr(int32(347)).(*int32),
						Bytes:        gotestparrot.Ptr(int32(3305164)).(*int32),
						Composer:     gotestparrot.Ptr("Philip Glass").(*string),
						GenreId:      gotestparrot.Ptr(int32(10)).(*int32),
						MediaTypeId:  int32(2),
						Milliseconds: int32(206005),
						Name:         "Koyaanisqatsi",
						TrackId:      int32(3503),
						UnitPrice:    0.99,
					},
				}},
			}},
			Artist: model.Artist{
				ArtistId: int32(275),
				Name:     gotestparrot.Ptr("Philip Glass Ensemble").(*string),
			},
		},
	}})
	gotestparrot.R.Load("TestSelect", []gotestparrot.Recording{{
		Key: 0,
		Value: `
SELECT "Album"."AlbumId" AS "Album.AlbumId",
     "Album"."Title" AS "Album.Title",
     "Album"."ArtistId" AS "Album.ArtistId"
FROM chinook."Album"
ORDER BY "Album"."AlbumId" ASC;
`,
	}, {
		Key:   1,
		Value: 347,
	}, {
		Key: 2,
		Value: model.Album{
			AlbumId:  int32(1),
			ArtistId: int32(1),
			Title:    "For Those About To Rock We Salute You",
		},
	}, {
		Key: 3,
		Value: model.Album{
			AlbumId:  int32(347),
			ArtistId: int32(275),
			Title:    "Koyaanisqatsi (Soundtrack from the Motion Picture)",
		},
	}})
	gotestparrot.R.Load("TestSelfJoin", []gotestparrot.Recording{{
		Key: 0,
		Value: `
SELECT "Employee"."EmployeeId" AS "Employee.EmployeeId",
     "Employee"."FirstName" AS "Employee.FirstName",
     "Employee"."LastName" AS "Employee.LastName",
     "Manager"."EmployeeId" AS "Manager.EmployeeId",
     "Manager"."FirstName" AS "Manager.FirstName",
     "Manager"."LastName" AS "Manager.LastName"
FROM chinook."Employee"
     LEFT JOIN chinook."Employee" AS "Manager" ON ("Employee"."ReportsTo" = "Manager"."EmployeeId")
ORDER BY "Employee"."EmployeeId";
`,
	}, {
		Key:   1,
		Value: []interface{}{},
	}, {
		Key:   2,
		Value: 8,
	}, {
		Key: 3,
		Value: []struct {
			model.Employee
			Manager *model.Employee `alias:"Manager.*"`
		}{{Employee: model.Employee{
			EmployeeId: int32(1),
			FirstName:  "Andrew",
			LastName:   "Adams",
		}}, {
			Employee: model.Employee{
				EmployeeId: int32(2),
				FirstName:  "Nancy",
				LastName:   "Edwards",
			},
			Manager: &model.Employee{
				EmployeeId: int32(1),
				FirstName:  "Andrew",
				LastName:   "Adams",
			},
		}},
	}})
	gotestparrot.R.Load("TestSubQueriesForQuotedNames", []gotestparrot.Recording{{
		Key: 0,
		Value: `
SELECT "first10Artist"."Artist.ArtistId" AS "Artist.ArtistId",
     "first10Artist"."Artist.Name" AS "Artist.Name",
     "first10Albums"."Album.AlbumId" AS "Album.AlbumId",
     "first10Albums"."Album.Title" AS "Album.Title",
     "first10Albums"."Album.ArtistId" AS "Album.ArtistId"
FROM (
          SELECT "Artist"."ArtistId" AS "Artist.ArtistId",
               "Artist"."Name" AS "Artist.Name"
          FROM chinook."Artist"
          ORDER BY "Artist"."ArtistId"
          LIMIT $1
     ) AS "first10Artist"
     INNER JOIN (
          SELECT "Album"."AlbumId" AS "Album.AlbumId",
               "Album"."Title" AS "Album.Title",
               "Album"."ArtistId" AS "Album.ArtistId"
          FROM chinook."Album"
          ORDER BY "Album"."AlbumId"
          LIMIT $2
     ) AS "first10Albums" ON ("first10Artist"."Artist.ArtistId" = "first10Albums"."Album.ArtistId")
ORDER BY "first10Artist"."Artist.ArtistId";
`,
	}, {
		Key:   1,
		Value: []interface{}{int64(10), int64(10)},
	}, {
		Key:   2,
		Value: 8,
	}, {
		Key: 3,
		Value: []struct {
			model.Artist
			Album []model.Album
		}{{
			Album: []model.Album{{
				AlbumId:  int32(1),
				ArtistId: int32(1),
				Title:    "For Those About To Rock We Salute You",
			}, {
				AlbumId:  int32(4),
				ArtistId: int32(1),
				Title:    "Let There Be Rock",
			}},
			Artist: model.Artist{
				ArtistId: int32(1),
				Name:     gotestparrot.Ptr("AC/DC").(*string),
			},
		}, {
			Album: []model.Album{{
				AlbumId:  int32(2),
				ArtistId: int32(2),
				Title:    "Balls to the Wall",
			}, {
				AlbumId:  int32(3),
				ArtistId: int32(2),
				Title:    "Restless and Wild",
			}},
			Artist: model.Artist{
				ArtistId: int32(2),
				Name:     gotestparrot.Ptr("Accept").(*string),
			},
		}},
	}})
	gotestparrot.R.Load("TestUnionForQuotedNames", []gotestparrot.Recording{{
		Key: 0,
		Value: `
(
     SELECT "Album"."AlbumId" AS "Album.AlbumId",
          "Album"."Title" AS "Album.Title",
          "Album"."ArtistId" AS "Album.ArtistId"
     FROM chinook."Album"
     WHERE "Album"."AlbumId" = $1
)
UNION ALL
(
     SELECT "Album"."AlbumId" AS "Album.AlbumId",
          "Album"."Title" AS "Album.Title",
          "Album"."ArtistId" AS "Album.ArtistId"
     FROM chinook."Album"
     WHERE "Album"."AlbumId" = $2
)
ORDER BY "Album.AlbumId";
`,
	}, {
		Key:   1,
		Value: []interface{}{int64(1), int64(2)},
	}, {
		Key:   2,
		Value: 2,
	}, {
		Key: 3,
		Value: []model.Album{{
			AlbumId:  int32(1),
			ArtistId: int32(1),
			Title:    "For Those About To Rock We Salute You",
		}, {
			AlbumId:  int32(2),
			ArtistId: int32(2),
			Title:    "Balls to the Wall",
		}},
	}})
}
