// Code generated by testparrot. DO NOT EDIT.

package postgres

import gotestparrot "github.com/xtruder/go-testparrot"

func init() {
	gotestparrot.R.Load("TestLockTable", []gotestparrot.Recording{{
		Key: 0,
		Value: `
LOCK TABLE dvds.address IN ACCESS SHARE MODE;
`,
	}, {
		Key: 1,
		Value: `
LOCK TABLE dvds.address IN ROW SHARE MODE;
`,
	}, {
		Key: 2,
		Value: `
LOCK TABLE dvds.address IN ROW EXCLUSIVE MODE;
`,
	}, {
		Key: 3,
		Value: `
LOCK TABLE dvds.address IN SHARE UPDATE EXCLUSIVE MODE;
`,
	}, {
		Key: 4,
		Value: `
LOCK TABLE dvds.address IN SHARE MODE;
`,
	}, {
		Key: 5,
		Value: `
LOCK TABLE dvds.address IN SHARE ROW EXCLUSIVE MODE;
`,
	}, {
		Key: 6,
		Value: `
LOCK TABLE dvds.address IN EXCLUSIVE MODE;
`,
	}, {
		Key: 7,
		Value: `
LOCK TABLE dvds.address IN ACCESS EXCLUSIVE MODE;
`,
	}, {
		Key: 8,
		Value: `
LOCK TABLE dvds.address IN ACCESS SHARE MODE NOWAIT;
`,
	}, {
		Key: 9,
		Value: `
LOCK TABLE dvds.address IN ROW SHARE MODE NOWAIT;
`,
	}, {
		Key: 10,
		Value: `
LOCK TABLE dvds.address IN ROW EXCLUSIVE MODE NOWAIT;
`,
	}, {
		Key: 11,
		Value: `
LOCK TABLE dvds.address IN SHARE UPDATE EXCLUSIVE MODE NOWAIT;
`,
	}, {
		Key: 12,
		Value: `
LOCK TABLE dvds.address IN SHARE MODE NOWAIT;
`,
	}, {
		Key: 13,
		Value: `
LOCK TABLE dvds.address IN SHARE ROW EXCLUSIVE MODE NOWAIT;
`,
	}, {
		Key: 14,
		Value: `
LOCK TABLE dvds.address IN EXCLUSIVE MODE NOWAIT;
`,
	}, {
		Key: 15,
		Value: `
LOCK TABLE dvds.address IN ACCESS EXCLUSIVE MODE NOWAIT;
`,
	}})
}
