// Code generated by testparrot. DO NOT EDIT.

package mariadb

import gotestparrot "github.com/xtruder/go-testparrot"

func init() {
	gotestparrot.R.Load("TestDeleteExecContext", []gotestparrot.Recording{{
		Key: 0,
		Value: `
DELETE FROM test_sample.link
WHERE link.name IN (?, ?);
`,
	}, {
		Key:   1,
		Value: []interface{}{"Gmail", "Outlook"},
	}})
	gotestparrot.R.Load("TestDeleteQueryContext", []gotestparrot.Recording{{
		Key: 0,
		Value: `
DELETE FROM test_sample.link
WHERE link.name IN (?, ?);
`,
	}, {
		Key:   1,
		Value: []interface{}{"Gmail", "Outlook"},
	}})
	gotestparrot.R.Load("TestDeleteWithWhere", []gotestparrot.Recording{{
		Key: 0,
		Value: `
DELETE FROM test_sample.link
WHERE link.name IN (?, ?);
`,
	}, {
		Key:   1,
		Value: []interface{}{"Gmail", "Outlook"},
	}})
	gotestparrot.R.Load("TestDeleteWithWhereOrderByLimit", []gotestparrot.Recording{{
		Key: 0,
		Value: `
DELETE FROM test_sample.link
WHERE link.name IN (?, ?)
ORDER BY link.name
LIMIT ?;
`,
	}, {
		Key:   1,
		Value: []interface{}{"Gmail", "Outlook", int64(1)},
	}})
}
