// Code generated by testparrot. DO NOT EDIT.

package mariadb

import gotestparrot "github.com/xtruder/go-testparrot"

func init() {
	gotestparrot.R.Load("TestWITH_And_SELECT", []gotestparrot.Recording{{
		Key: 0,
		Value: `
WITH sales_rep AS (
     SELECT staff.staff_id AS "staff.staff_id",
          (CONCAT(staff.first_name, staff.last_name)) AS "sales_rep_full_name"
     FROM dvds.staff
),customer_sales_rep AS (
     SELECT (CONCAT(customer.first_name, customer.last_name)) AS "customer_name",
          sales_rep.sales_rep_full_name AS "sales_rep_full_name"
     FROM sales_rep
          INNER JOIN dvds.store ON (store.manager_staff_id = sales_rep.` + "`" + `staff.staff_id` + "`" + `)
          INNER JOIN dvds.customer ON (customer.store_id = store.store_id)
)
SELECT customer_sales_rep.customer_name AS "customer_name",
     customer_sales_rep.sales_rep_full_name AS "sales_rep_full_name"
FROM customer_sales_rep
LIMIT ?;
`,
	}, {
		Key:   1,
		Value: []interface{}{int64(10)},
	}, {
		Key: 2,
		Value: []struct {
			CustomerName     string
			SalesRepFullName string
		}{{
			CustomerName:     "MARYSMITH",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "PATRICIAJOHNSON",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "LINDAWILLIAMS",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "ELIZABETHBROWN",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "MARIAMILLER",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "DOROTHYTAYLOR",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "NANCYTHOMAS",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "HELENHARRIS",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "DONNATHOMPSON",
			SalesRepFullName: "MikeNew name",
		}, {
			CustomerName:     "RUTHMARTINEZ",
			SalesRepFullName: "MikeNew name",
		}},
	}})
}
