// Code generated by testparrot. DO NOT EDIT.

package postgres

import gotestparrot "github.com/xtruder/go-testparrot"

func init() {
	gotestparrot.R.Load("TestSelectSets", []gotestparrot.Recording{{
		Key: 0,
		Value: `
(
     SELECT table1.col_bool AS "table1.col_bool"
     FROM db.table1
)
UNION
(
     SELECT table2.col_bool AS "table2.col_bool"
     FROM db.table2
);
`,
	}, {
		Key:   1,
		Value: []interface{}{},
	}, {
		Key: 2,
		Value: `
(
     SELECT table1.col_bool AS "table1.col_bool"
     FROM db.table1
)
UNION ALL
(
     SELECT table2.col_bool AS "table2.col_bool"
     FROM db.table2
);
`,
	}, {
		Key:   3,
		Value: []interface{}{},
	}, {
		Key: 4,
		Value: `
(
     SELECT table1.col_bool AS "table1.col_bool"
     FROM db.table1
)
INTERSECT
(
     SELECT table2.col_bool AS "table2.col_bool"
     FROM db.table2
);
`,
	}, {
		Key:   5,
		Value: []interface{}{},
	}, {
		Key: 6,
		Value: `
(
     SELECT table1.col_bool AS "table1.col_bool"
     FROM db.table1
)
INTERSECT ALL
(
     SELECT table2.col_bool AS "table2.col_bool"
     FROM db.table2
);
`,
	}, {
		Key:   7,
		Value: []interface{}{},
	}, {
		Key: 8,
		Value: `
(
     SELECT table1.col_bool AS "table1.col_bool"
     FROM db.table1
)
EXCEPT
(
     SELECT table2.col_bool AS "table2.col_bool"
     FROM db.table2
);
`,
	}, {
		Key:   9,
		Value: []interface{}{},
	}, {
		Key: 10,
		Value: `
(
     SELECT table1.col_bool AS "table1.col_bool"
     FROM db.table1
)
EXCEPT ALL
(
     SELECT table2.col_bool AS "table2.col_bool"
     FROM db.table2
);
`,
	}, {
		Key:   11,
		Value: []interface{}{},
	}})
}
